### ISSUE TITLE
Restore an orphan commit from the v0.0.0 tag

### ISSUE THREAD

**Issue by tkelman** [soundcloud/MinimalPerfectHashes.jl#7]
Hi, no major problem here, was just scraping some data for old package releases and found that the commit c2223cc0288f78729f3dc149b4026410b241bba8 which is tagged in https://github.com/JuliaLang/METADATA.jl/blob/metadata-v2/MinimalPerfectHashes/versions/0.0.0/sha1 is not in the history of any branches and wasn't pushed as a git tag. Just so this commit can be checked out without getting a "fatal: reference is not a tree" error, it would be good if someone with commit access could do
```
git remote add tkelman https://github.com/tkelman/MinimalPerfectHashes.jl
git fetch tkelman
git checkout c2223cc0288f78729f3dc149b4026410b241bba8
git tag v0.0.0
git push origin v0.0.0
```

That is all, if someone does that, we can go ahead and close this. Thanks!

**Comment by mweiden** [comment]
@tkelman done, ty
